import Head from 'next/head';
import Image from 'next/image';
import Welcome from '../components/welcome';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='h-screen w-screen bg-gray-100'>
        <div>
          <Welcome />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
